
export const mockEvents = [
    {
        code: "WAD-2025",
        title: "World Architecture Day: The Future of Urbanism",
        date: "2025-10-06T10:00:00Z",
        type: "Talk",
        focus: "Architecture",
        description: "A panel discussion with leading architects on sustainable urban development and smart cities.",
        image: "https://picsum.photos/800/450?random=1",
        aiHint: "modern city architecture",
        platform: "Zoom",
        location: "Online",
        longDescription: "In celebration of World Architecture Day, join us for a thought-provoking panel discussion featuring some of the world's most innovative architects. We will explore the future of urbanism, focusing on the roles of sustainability, technology, and community in shaping the cities of tomorrow. This is a unique opportunity to gain insights from industry leaders and participate in a global conversation.",
        speakers: [
            { name: "Dr. Elena Vance", title: "Urban Futurist & Architect", bio: "Dr. Vance is a renowned architect and urban planner whose work focuses on creating resilient and human-centric cities.", avatar: "https://i.pravatar.cc/150?u=speaker1" },
            { name: "Marcus Thorne", title: "Principal, Thorne Architects", bio: "Marcus Thorne leads an award-winning firm known for its groundbreaking sustainable high-rise designs.", avatar: "https://i.pravatar.cc/150?u=speaker2" },
        ],
        agenda: [
            { time: "10:00 AM", topic: "Opening Remarks & Introduction" },
            { time: "10:15 AM", topic: "Panel Discussion: The Next Decade of Urban Design" },
            { time: "11:15 AM", topic: "Live Q&A with Audience" },
            { time: "11:45 AM", topic: "Closing Remarks" },
        ]
    },
    {
        code: "AI-DESIGN-01",
        title: "Intro to AI in Architectural Design",
        date: "2025-10-15T14:00:00Z",
        type: "Workshop",
        focus: "AI in Design",
        description: "A hands-on workshop exploring generative AI tools for conceptual design and visualization.",
        image: "https://picsum.photos/800/450?random=2",
        aiHint: "ai design",
        platform: "Discord",
        location: "Aether Community Discord",
        longDescription: "Unlock the power of Artificial Intelligence in your design process. This hands-on workshop will guide you through the latest AI tools that are revolutionizing architectural design. You will learn how to generate concepts, create stunning visualizations, and optimize your workflows. No prior AI experience is required, just a passion for the future of design.",
        speakers: [
            { name: "Jasmine Lee", title: "Computational Designer", bio: "Jasmine is a pioneer in the application of AI in architecture, with a portfolio of award-winning generative projects.", avatar: "https://i.pravatar.cc/150?u=speaker3" },
        ],
        agenda: [
            { time: "2:00 PM", topic: "Introduction to Generative AI" },
            { time: "2:30 PM", topic: "Hands-on Session: Midjourney for Architects" },
            { time: "3:30 PM", topic: "Advanced Techniques & Prompts" },
            { time: "4:00 PM", topic: "Project Showcase & Feedback" },
        ]
    },
    {
        code: "COM-MEET-Q4",
        title: "Aether Community Quarterly Meetup",
        date: "2025-10-22T18:00:00Z",
        type: "Meetup",
        focus: "General",
        description: "Connect with fellow Aether members, share your projects, and hear community updates.",
        image: "https://picsum.photos/800/450?random=3",
        aiHint: "people meeting",
        platform: "Twitter Spaces",
        location: "Live on X (Twitter)",
        longDescription: "Join us for our quarterly community meetup! This is a casual event to connect with fellow members, showcase the amazing projects you've been working on, and get the latest updates from the Aether team. We'll have open mic sessions, special announcements, and plenty of opportunities to network.",
        speakers: [
             { name: "Aether Community Team", title: "Hosts", bio: "Your friendly community managers and leads.", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=aether" },
        ],
        agenda: null
    },
    {
        code: "SUST-CHALLENGE",
        title: "Sustainable Housing Design Challenge",
        date: "2025-11-01T09:00:00Z",
        type: "Challenge",
        focus: "Sustainable Architecture",
        description: "A month-long design challenge to create innovative, eco-friendly housing solutions.",
        image: "https://picsum.photos/800/450?random=4",
        aiHint: "sustainable housing",
        platform: "Aether Platform",
        location: "Submissions via our website",
        longDescription: "Announcing the Aether Sustainable Housing Challenge! We invite designers and architects from around the world to develop innovative and eco-friendly housing solutions for the future. Over one month, you will research, design, and present a project that addresses key sustainability goals. Winners will receive prizes and be featured on the Aether homepage.",
        speakers: [],
        agenda: [
            { time: "Nov 1", topic: "Challenge Kick-off & Briefing" },
            { time: "Nov 15", topic: "Mid-point Check-in & Mentorship Session" },
            { time: "Nov 30", topic: "Submission Deadline" },
            { time: "Dec 8", topic: "Winners Announcement" },
        ]
    },
    {
        code: "WEB3-ARCH-01",
        title: "Exploring Web3 for Architects",
        date: "2025-11-10T16:00:00Z",
        type: "Talk",
        focus: "Web3",
        description: "Learn how blockchain and decentralized technologies are impacting the built environment.",
        image: "https://picsum.photos/800/450?random=5",
        aiHint: "blockchain architecture",
        platform: "Zoom",
        location: "Online",
        longDescription: "Web3 is more than just cryptocurrency. In this talk, we'll dive into how blockchain, NFTs, and the metaverse are creating new opportunities and challenges for architects and designers. From tokenizing real estate to designing virtual worlds, discover how the decentralized web is set to reshape the built environment.",
        speakers: [
            { name: "Leo Chen", title: "Founder, Metaprop", bio: "Leo is a venture capitalist and thought leader at the intersection of real estate, technology, and Web3.", avatar: "https://i.pravatar.cc/150?u=speaker4" },
        ],
        agenda: null,
    },
    {
        code: "COMP-DESIGN-ADV",
        title: "Advanced Computational Design",
        date: "2025-11-18T11:00:00Z",
        type: "Workshop",
        focus: "Computational Design",
        description: "An advanced workshop on parametric modeling and algorithmic design for complex geometries.",
        image: "https://picsum.photos/800/450?random=6",
        aiHint: "parametric design",
        platform: "Discord",
        location: "Aether Community Discord",
        longDescription: "Take your computational design skills to the next level. This advanced workshop is for designers who are already comfortable with parametric modeling and want to explore complex geometries, algorithmic design, and optimization scripts. We will be working with Rhino, Grasshopper, and Python to create sophisticated architectural forms.",
        speakers: [
             { name: "Sofia Al-Jamil", title: "Architectural Engineer", bio: "Sofia is an expert in computational design and has taught workshops at leading universities worldwide.", avatar: "https://i.pravatar.cc/150?u=speaker5" },
        ],
        agenda: [
            { time: "11:00 AM", topic: "Recap of Parametric Principles" },
            { time: "11:30 AM", topic: "Advanced Grasshopper Techniques" },
            { time: "1:00 PM", topic: "Lunch Break" },
            { time: "2:00 PM", topic: "Intro to Rhino.Python scripting" },
            { time: "3:30 PM", topic: "Project Work & 1-on-1 Mentoring" },
        ]
    }
];
